origins:
        "Simple": {
                store: "Simple",
                source: "Source",
                title: "Simple",
                store_settings: {
                        url: "http://localhost:4567",
                }
        }

